<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Add New Category</h4>
      </div>
      <?php
      //$form->setAttribute('action', $this->url('category', array('action' => 'add')));
        $form->prepare();

        echo $this->form()->openTag($form); ?>

      <div class="modal-body">
        <?php

        
        echo $this->formHidden($form->get('id'));
        echo $this->formRow($form->get('name'));

        //echo $this->formSubmit($form->get('submit'));
        

         ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <input type="button" id="addbtn" class="btn btn-primary" name = "submit" value = "Add">
      </div>
      <?php echo $this->form()->closeTag(); ?>
    </div>
  </div>